version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../src:/var/www

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

  nginx-letsencrypt:
    image: linuxserver/letsencrypt
    container_name: nginx-letsencrypt
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/letsencrypt:/config
    environment:
      - EMAIL=frederic.triquet+letsencrypt@gmail.com
      - URL=rodger.sytes.net
      - VALIDATION=http
      - TZ=Europe/Paris
      - PUID=0
      - PGID=0
