version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


# https-portal:
#   image: steveltn/https-portal:1
#   ports:
#     - '80:80'
#     - '443:443'
#   links:
#     - blog
#   restart: always
#   environment:
#     DOMAINS: 'blog.example.com -> http://blog:80'
#     STAGE: local
#     DOMAINS: 'example.com'
#     # STAGE: 'production'
#     # FORCE_RENEW: 'true'

# blog:
#   image: richarvey/nginx-php-fpm:latest
#   ports:
#     - '80:80'
