https-portal:
  image: steveltn/https-portal:1
  ports:
    - '80:80'
    - '443:443'
  links:
    - php
  restart: always
  environment:
    DOMAINS: 'rodger.sytes.net -> http://php:80'
    STAGE: 'production'
    # FORCE_RENEW: 'true'

#wordpress:
#  image: wordpress
#  links:
#    - db:mysql

php:
  image: romeoz/docker-apache-php
  volumes:
    - ./html:/var/www/app
