version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - php
    restart: always
    environment:
      DOMAINS: 'rodger.sytes.net -> http://php:80'
      STAGE: 'production'
      # FORCE_RENEW: 'true'

  php:
    #image: romeoz/docker-apache-php
    build:
      context: ./docker/php
    volumes:
      - ./html:/var/www/app:rw
      #- ./src/Pico:/var/www/app
